// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwazsAEzFfGpq1AVSLKB45C-CUaTIxTro',
    appId: '1:814483622041:web:deeab9f3218328b4ab5008',
    messagingSenderId: '814483622041',
    projectId: 'student-directory-app-314f5',
    authDomain: 'student-directory-app-314f5.firebaseapp.com',
    storageBucket: 'student-directory-app-314f5.firebasestorage.app',
    measurementId: 'G-CEPM6HGC05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkB9z0FWAAxBed9xJblZfSHJs9BSrvTM',
    appId: '1:814483622041:android:68de2ac22ac04b64ab5008',
    messagingSenderId: '814483622041',
    projectId: 'student-directory-app-314f5',
    storageBucket: 'student-directory-app-314f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB335OoM0h_Ee9vlal6O0dKUTWzK6GMRMU',
    appId: '1:814483622041:ios:31b060a9239b8f23ab5008',
    messagingSenderId: '814483622041',
    projectId: 'student-directory-app-314f5',
    storageBucket: 'student-directory-app-314f5.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB335OoM0h_Ee9vlal6O0dKUTWzK6GMRMU',
    appId: '1:814483622041:ios:31b060a9239b8f23ab5008',
    messagingSenderId: '814483622041',
    projectId: 'student-directory-app-314f5',
    storageBucket: 'student-directory-app-314f5.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwazsAEzFfGpq1AVSLKB45C-CUaTIxTro',
    appId: '1:814483622041:web:0705f48b50fb2d7bab5008',
    messagingSenderId: '814483622041',
    projectId: 'student-directory-app-314f5',
    authDomain: 'student-directory-app-314f5.firebaseapp.com',
    storageBucket: 'student-directory-app-314f5.firebasestorage.app',
    measurementId: 'G-WDKEZXQREF',
  );
}
